### ISSUE TITLE
Peer-Code-Review

### ISSUE THREAD

**Issue by d2ndjim** [virag-ky/Microverse-Portfolio#11]
Great work with the index.html indentation. However, I think it could be more semantic i.e instead of having divs, maybe you can separate them into sections.

**Comment by ciraganenicole** [comment]
Congratulations on implementing the project with a highly clean and organized code. However, you should just follow all requirements as asked and it will cool 😃 

Other than that, fantastic job. Keep moving forward 💪 

All the best
