### ISSUE TITLE
Week 3 Day 2 Morning Session

### ISSUE THREAD

**Issue by HamzaAnwar1998** [virag-ky/Microverse-Portfolio#7]
We are going to review the UI and code.

**Comment by misheck12** [comment]
@virag-ky this is splendid the button effect is so attractive keep it up. 
![image](https://user-images.githubusercontent.com/49679254/155086577-2d2654c6-082d-4271-92e2-2fa8a4c9da52.png)

**Comment by HamzaAnwar1998** [comment]
Nice design implemented, neat and clean code, in short, Great job done.

**Comment by white3d** [comment]
Hi @virag-ky,

Congratulations! 🎉 Project Approved ✅
You nailed it from the first try 🎊
Your project is complete! There is nothing else to say other than... it's time to merge it 🚀

To Highlight:

 The Pull Request has a proper title and description. ✔️
 You have added a descriptive Readme file. Good Job. ✔️
 There is no linter error is present. ✔️
 Project has met all the technical aspects you needed for this project! ✔️
 There is no difference between your project and the Figma design ✔️
Cheers and Happy coding and Keep rocking! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
